
# ================= 多语言 Agent 映射字典 =================
AGENT_NAME_MAPPING_TC = {
    "General": ["通用AI代理"],
    "Chatbot": ["聊天機器人"],
    "LLM Only": ["大型語言模型"],
    "Problem Statement": ["問題陳述"],
    "Ideation": ["解決方案的構思"],
    "Feasibility Analysis": ["項目可行性分析"],
    "Market Analysis": ["市場分析報告"],
    "Competitive Analysis": ["競爭分析"],
    "Business Forecasting": ["商務規劃"],
    "Objective": ["專案目標"],
    "Operation Strategy": ["運營策略"],
    "R&D Strategic Plan": ["研發戰略"],
    "Development Plan": ["公司發展規劃"],
    "CRM strategy": ["客戶關係管理策略"],
    "ESG Strategy": ["ESG 策略"],
    "Negotiation Strategies": ["談判策略", "談判方案"],
    "Strategic Crisis Management": ["策略性危機管理"],
    "Risk Management plan": ["危機管理計劃"],
    "Sustainability Plan": ["可持續發展計劃"],
    "Resource Management Plan": ["資源管理計劃"],
    "Business Model Evaluation": ["商業模式評估"],
    "Marketing Model Evaluation": ["行銷模式評估"],
    "Sales Model Evaluation": ["銷售模式評估"],
    "Technology Evaluation": ["技術評估"],
    "Supply Chain Evaluation": ["供應鏈評估"],
    "Research Intro": ["研究簡介"],
    "Literature Review": ["文獻綜述"],
    "Research Proposal": ["項目研究計劃"],
    "Research Methodology": ["研究方法"],
    "Research Experiment": ["研究實驗"],
    "Project Proposal": ["項目建議書"],
    "RnD Project Plan": ["R&D 項目計劃"],
    "Commercialization": ["商業化項目計劃"],
    "Product Dev Plan": ["開發產品計劃"],
    "Product Description": ["產品描述"],
    "Marketing Plan": ["市場策劃"],
    "Sales Strategic Plan": ["銷售策略計劃"],
    "Event Planner": ["活動策劃者"],
    "Advertisement Plan": ["廣告計劃"],
    "Exhibition Plan": ["展覽平面圖"],
    "Script": ["講稿"],
    "Press Release": ["新聞稿"],
    "EDM": ["電子郵件行銷"],
    "Blog Article": ["文章撰寫"],
    "Soc Media Post": ["社交媒體帖子"],
    "Lecture Syllabus": ["課程大綱"],
    "Lecture Note": ["課堂講義"],
    "Lecture Chapter": ["課程簡報"],
    "Lecture Q&A": ["課堂問答"],
    "Lecture Exam": ["課程試卷"],
    "Yearly Company Calendar": ["年度公司行事曆"],
    "HR Strategy Plan": ["人力資源策略計劃"],
    "Staff Handbook": ["員工手冊"],
    "Appraisal Guideline": ["評估指引"],
    "Staff Feedback Guideline": ["員工反饋指引"],
    "Recruitment Plan": ["招聘計劃"],
    "Job description and Job post": ["招聘啟事"],
    "Interview Question": ["面試問題"],
    "Recruitment Written Test": ["招聘筆試"],
    "Employment Contract": ["僱傭合同"],
    "Company Letter": ["公司信函"],
    "Announcement": ["公告"],
    "Company Policy": ["公司政策"],
    "Procurement Guideline": ["採購指引"],
    "Workflow Guideline": ["工作流程指引"],
    "Non-Disclosure Agreement": ["保密協議"],
    "Agreement": ["協定"],
    "Intellectual Property Claim": ["知識產權申索"],
    "Licensing Agreement": ["授權協議"],
    "Collaboration Document (MoU or LOI)": ["合作文件 或 意向書"],
    "Questionnaire Form": ["問卷表格"],
    "Performance Evaluation Form": ["績效評估表"],
    "Notice Writing": ["通告撰寫"],
    "KPI Guideline": ["KPI 指南"],
    "Terms Sheet": ["條款表"],
    "Appreciation Letter": ["感謝信"],
    "Recommendation Letter": ["推薦信"],
    "Supporting Letter": ["支援信"],
    "Warning Letter": ["警告信"],
    "Complaint Letter": ["投訴信"],
    "Budget and Offer": ["財務規劃"],
    "Investment Market Survey": ["投資市場調查"],
    "Investment Annual Review": ["投資年度回顧"],
    "Investment Project Review": ["投資項目評估"],
    "Investment Portfolio Proposal": ["投資組合提案"],
    "Investment Execution Plan": ["投資執行計劃"],
    "Event Survey": ["活動調查"],
    "Marketing Survey": ["市場調查"],
    "Advertisement Survey": ["廣告調查"],
    "Exhibition Survey": ["展會概況"],
    "Sales Survey": ["銷售調查"],
    "Speech Topic Ideation": ["演講主題構思"],
    "Speech Topic Review": ["演講主題回顧"],
    "Speech Brief": ["演講介紹"],
    "Speech Note": ["語音記錄"],
    "Speech Script": ["語音腳本"],
    "Resume or CV": ["履歷"],
    "Biography": ["個人簡介"],
    "Job Application Letter": ["求職信"],
    "Essay Writer": ["論文撰寫"],
    "Self-Learning Q&A": ["自學問答題"],
    "Gathering Idea with family, friends, etc": ["聚集理念"],
    "Travel Idea": ["旅行點子"],
    "Skill Idea": ["技能理念"],
    "Gift Idea": ["禮品創意"],
    "Activity Idea": ["活動理念"],

    "Crisis Management": ["危機管理", "應急管理"],
    "Market Research": ["市場調研"],
    "Competitor Analysis": ["競爭對手分析"],
    "Corporate Strategy": ["企業戰略"],
    "Operational Efficiency": ["運營效率優化"],
    "Data Analysis": ["數據分析"],
    "Financial Report": ["財務報告"],
    "Customer Insight": ["客戶洞察"],
    "Team Building": ["團隊建設"],
    "Innovation Management": ["創新管理"],
    "Digital Transformation": ["數位轉型"],
    "Brand Strategy": ["品牌策略"],
    "Content Strategy": ["內容策略"],
    "User Experience Design": ["用戶體驗設計"],
    "Project Management": ["項目管理"],
    "Agile Methodology": ["敏捷開發方法"],
    "Quality Assurance": ["品質保證"],
    "Software Development": ["軟體開發"],
    "Hardware Development": ["硬體開發"],
    "Market Entry Strategy": ["市場進入策略"],
    "Pricing Strategy": ["定價策略"],
    "Distribution Strategy": ["分銷策略"],
    "Customer Retention": ["客戶留存策略"],
    "Internal Communication": ["內部溝通"],
    "Conflict Resolution": ["衝突解決"],
    "Networking": ["人際網路拓展"],
    "Time Management": ["時間管理"],
    "Personal Productivity": ["個人效能"],
    "Goal Setting": ["目標設定"],
    "Mind Mapping": ["心智圖"],
    "Brainstorming": ["腦力激盪"]
}
# ================= 自动生成：繁中 -> 英文 反向映射字典 =================
TC_TO_ENG_MAPPING = {}
for eng_key, tc_list in AGENT_NAME_MAPPING_TC.items():
    for tc_name in tc_list:
        TC_TO_ENG_MAPPING[tc_name] = eng_key